image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  report_card: {}
  catapult:
    url: $$catapult_url
    application: "log-monitor-es"
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/log-monitor-es
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
script:
- make build
