
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.23.13"

[[constraint]]
  name = "github.com/signalfx/golib"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "^6.23.0"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.81"
