routes:
  search-error:
    matchers:
      title: [ "failed-search" ]
    output:
      type: "notifications"
      channel: "#alerts-staging-infra"
      icon: ":elasticsearch:"
      message: "Failed elastic search query.  Is kibana down?\n>%{error}"
      user: "log-monitor-es"
